version: '3.7'

networks:
  content-network:

services:
  content-db:
    image: content-db:0.0.1
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: content-db
    networks:
      - content-network
    env_file:
      - .env
  content-service:
    image: content-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: content-service
    depends_on:
      - content-db
    networks:
      - content-network
    ports:
      - "8081:8081"
    env_file:
      - .env