version: '3.7'

networks:
  content-network:

volumes:
  data:
  dblog:
  servicelog:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /mnt/disks/$DEPLOYMENT_ENV-contentually/spring/logs

services:
  content-db:
    image: content-db:0.0.1
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: content-db
    networks:
      - content-network
    environment:
      - DEPLOYMENT_ENV
    volumes:
      - type: volume
        source: data
        target: /data/db
      - type: volume
        source: dblog
        target: /var/log/mongodb
      - type: bind
        source: /mnt/disks/secrets
        target: /mnt/disks/secrets
        read_only: true
  content-service:
    image: content-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: content-service
    depends_on:
      - content-db
    networks:
      - content-network
    ports:
      - "8081:8081"
    environment:
      - DEPLOYMENT_ENV
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV}
    volumes:
      - type: volume
        source: servicelog
        target: /var/log/spring
      - type: bind
        source: /mnt/disks/secrets
        target: /mnt/disks/secrets
        read_only: true
