version: '3.7'

networks:
  content-network:

services:
  content-db:
    image: content-db:0.0.1
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: content-db
    networks:
      - content-network
    environment:
      - DEPLOYMENT_ENV
    volumes:
      - /mnt/disks/${DEPLOYMENT_ENV}-contentually/content/db/data:/data/db:rw
      - /mnt/disks/${DEPLOYMENT_ENV}-contentually/content/db/log:/var/log/mongodb:rw
      - /mnt/disks/${DEPLOYMENT_ENV}-contentually/content/secrets:/data/secrets:ro
  content-service:
    image: content-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: content-service
    depends_on:
      - content-db
    networks:
      - content-network
    ports:
      - "8081:8081"
    environment:
      - DEPLOYMENT_ENV
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV}
    volumes:
      - /mnt/disks/${DEPLOYMENT_ENV}-contentually/content/service/log:/var/log/content:rw
      - /mnt/disks/${DEPLOYMENT_ENV}-contentually/content/secrets:/data/secrets:ro
