version: '3.7'

networks:
  image-network:

volumes:
  data:
  dblog:
  servicelog:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /mnt/disks/$DEPLOYMENT_ENV-contentually/spring/logs

services:
  image-db:
    image: image-db:0.0.1
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: image-db
    networks:
      - image-network
    environment:
      - DEPLOYMENT_ENV
    volumes:
      - type: volume
        source: data
        target: /data/db
      - type: volume
        source: dblog
        target: /var/log/mongodb
      - type: bind
        source: /mnt/disks/secrets
        target: /mnt/disks/secrets
        read_only: true
  image-service:
    image: image-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: image-service
    depends_on:
      - image-db
    networks:
      - image-network
    ports:
      - "8082:8082"
    environment:
      - DEPLOYMENT_ENV
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV}
    volumes:
      - type: volume
        source: servicelog
        target: /var/log/spring
      - type: bind
        source: /mnt/disks/secrets
        target: /mnt/disks/secrets
        read_only: true
