version: '3.7'

networks:
  image-network:

services:
  image-db:
    image: image-db:0.0.1
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: image-db
    networks:
      - image-network
    volumes:
      - /mnt/disks/${DEPLOYMENT_ENV}-contentually/image/db/data:/data/db:rw
      - /mnt/disks/${DEPLOYMENT_ENV}-contentually/image/db/log:/var/log/mongodb:rw
    env_file:
      - .env
  image-service:
    image: image-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-service
    depends_on:
      - image-db
    networks:
      - image-network
    ports:
      - "8082:8082"
    volumes:
      - /mnt/disks/${DEPLOYMENT_ENV}-contentually/image/service/log:/var/log/image:rw
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV}