version: '3.7'

networks:
  image-network:

services:
  image-db:
    image: image-db:0.0.1
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: image-db
    networks:
      - image-network
    env_file:
      - .env
  image-service:
    image: image-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-service
    depends_on:
      - image-db
    networks:
      - image-network
    ports:
      - "8082:8082"
    env_file:
      - .env