version: '3.7'

networks:
  image-network:

services:
  image-db:
    image: image-db:0.0.1
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: image-db
    volumes:
      - /mnt/disks/dev-contentually/image/db/data:/data/db:rw
      - /mnt/disks/dev-contentually/image/db/log:/var/log/mongodb:rw
    networks:
      - image-network
    env_file:
      - .env
  image-service:
    image: image-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-service
    depends_on:
      - image-db
    volumes:
      - /mnt/disks/dev-contentually/image/service/log:/var/log/image:rw
    networks:
      - image-network
    ports:
      - "8082:8082"
    env_file:
      - .env