version: '3.7'

networks:
  image-network:

volumes:
  db-log:
  service-log:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /mnt/disks/${DEPLOYMENT_ENV}-contentually/logs/spring
  image-data:

services:
  image-db:
    image: image-db:0.0.1
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: image-db
    networks:
      - image-network
    environment:
      - DEPLOYMENT_ENV
    volumes:
      - type: volume
        source: image-data
        target: /data/db
      - type: volume
        source: db-log
        target: /var/log/mongodb
      - type: bind
        source: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        target: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        read_only: true
  image-service:
    image: image-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: image-service
    depends_on:
      - image-db
    networks:
      - image-network
    ports:
      - "8082:8082"
    environment:
      - DEPLOYMENT_ENV
      - SPRING_PROFILES_ACTIVE=$DEPLOYMENT_ENV
    volumes:
      - type: volume
        source: service-log
        target: /var/log/spring
      - type: bind
        source: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        target: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        read_only: true
