version: '3.7'

volumes:
  service-log:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /mnt/disks/${DEPLOYMENT_ENV}-contentually/logs/spring

services:
  graphql-service:
    image: graphql-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: graphql-service
    ports:
      - "8080:8080"
    environment:
      - DEPLOYMENT_ENV
      - SPRING_PROFILES_ACTIVE=$DEPLOYMENT_ENV
    volumes:
      - type: volume
        source: service-log
        target: /var/log/spring
