version: '3.7'

services:
  graphql-service:
    image: graphql-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: graphql-service
    ports:
      - "8080:8080"
    environment:
      - DEPLOYMENT_ENV
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV}
    volumes:
      - /mnt/disks/${DEPLOYMENT_ENV}-contentually/graphql/service/log:/var/log/graphql:rw
