version: '3.7'

volumes:
  servicelog:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /mnt/disks/$DEPLOYMENT_ENV-contentually/spring/logs

services:
  graphql-service:
    image: graphql-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: graphql-service
    ports:
      - "8080:8080"
    environment:
      - DEPLOYMENT_ENV
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV}
    volumes:
      - type: volume
        source: servicelog
        target: /var/log/spring
