version: '3.7'

networks:
  discovery-network:
  image-network:
  avatar-network:
  category-network:
  content-network:

volumes:
  db-log:
  service-log:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /mnt/disks/${DEPLOYMENT_ENV}-contentually/logs/spring
  image-data:
  avatar-data:
  category-data:
  content-data:

services:
  discovery-service:
    image: asia.gcr.io/${DEPLOYMENT_ENV}-contentually/discovery-service:0.0.1
    container_name: discovery-service
    restart: always
    networks:
      - discovery-network
    ports:
      - "8761:8761"
    environment:
      - DEPLOYMENT_ENV
    volumes:
      - type: volume
        source: service-log
        target: /var/log/spring
  image-db:
    image: asia.gcr.io/${DEPLOYMENT_ENV}-contentually/image-db:0.0.1
    container_name: image-db
    restart: always
    networks:
      - image-network
    ports:
      - "27018:27017"
    environment:
      - DEPLOYMENT_ENV
    volumes:
      - type: volume
        source: image-data
        target: /data/db
      - type: volume
        source: db-log
        target: /var/log/mongodb
      - type: bind
        source: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        target: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        read_only: true
  image-service:
    image: asia.gcr.io/${DEPLOYMENT_ENV}-contentually/image-service:0.0.1
    container_name: image-service
    restart: always
    depends_on:
      - image-db
      - discovery-service
    networks:
      - image-network
      - discovery-network
    ports:
      - "8082:8082"
    environment:
      - DEPLOYMENT_ENV
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV}
    volumes:
      - type: volume
        source: service-log
        target: /var/log/spring
      - type: bind
        source: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        target: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        read_only: true

  avatar-db:
    image: asia.gcr.io/${DEPLOYMENT_ENV}-contentually/avatar-db:0.0.1
    container_name: avatar-db
    restart: always
    networks:
      - avatar-network
    ports:
      - "27019:27017"
    environment:
      - DEPLOYMENT_ENV
    volumes:
      - type: volume
        source: avatar-data
        target: /data/db
      - type: volume
        source: db-log
        target: /var/log/mongodb
      - type: bind
        source: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        target: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        read_only: true
  avatar-service:
    image: asia.gcr.io/${DEPLOYMENT_ENV}-contentually/avatar-service:0.0.1
    container_name: avatar-service
    restart: always
    depends_on:
      - avatar-db
      - discovery-service
    networks:
      - avatar-network
      - discovery-network
    ports:
      - "8083:8083"
    environment:
      - DEPLOYMENT_ENV
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV}
    volumes:
      - type: volume
        source: service-log
        target: /var/log/spring
      - type: bind
        source: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        target: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        read_only: true

  category-db:
    image: asia.gcr.io/${DEPLOYMENT_ENV}-contentually/category-db:0.0.1
    container_name: category-db
    restart: always
    networks:
      - category-network
    ports:
      - "27020:27017"
    environment:
      - DEPLOYMENT_ENV
    volumes:
      - type: volume
        source: category-data
        target: /data/db
      - type: volume
        source: db-log
        target: /var/log/mongodb
      - type: bind
        source: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        target: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        read_only: true
  category-service:
    image: asia.gcr.io/${DEPLOYMENT_ENV}-contentually/category-service:0.0.1
    container_name: category-service
    restart: always
    depends_on:
      - category-db
      - discovery-service
    networks:
      - category-network
      - discovery-network
    ports:
      - "8084:8084"
    environment:
      - DEPLOYMENT_ENV
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV}
    volumes:
      - type: volume
        source: service-log
        target: /var/log/spring
      - type: bind
        source: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        target: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        read_only: true

  content-db:
    image: asia.gcr.io/${DEPLOYMENT_ENV}-contentually/content-db:0.0.1
    container_name: content-db
    restart: always
    networks:
      - content-network
    ports:
      - "27021:27017"
    environment:
      - DEPLOYMENT_ENV
    volumes:
      - type: volume
        source: content-data
        target: /data/db
      - type: volume
        source: db-log
        target: /var/log/mongodb
      - type: bind
        source: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        target: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        read_only: true
  content-service:
    image: asia.gcr.io/${DEPLOYMENT_ENV}-contentually/content-service:0.0.1
    container_name: content-service
    restart: always
    depends_on:
      - content-db
      - discovery-service
    networks:
      - content-network
      - discovery-network
    ports:
      - "8081:8081"
    environment:
      - DEPLOYMENT_ENV
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV}
    volumes:
      - type: volume
        source: service-log
        target: /var/log/spring
      - type: bind
        source: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        target: /mnt/disks/${DEPLOYMENT_ENV}-contentually/secrets/mongo
        read_only: true

  graphql-service:
    image: asia.gcr.io/${DEPLOYMENT_ENV}-contentually/graphql-service:0.0.1
    container_name: graphql-service
    restart: always
    depends_on:
      - image-service
      - avatar-service
      - category-service
      - content-service
      - discovery-service
    networks:
      - discovery-network
    ports:
      - "8080:8080"
    environment:
      - DEPLOYMENT_ENV
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV}
    volumes:
      - type: volume
        source: service-log
        target: /var/log/spring
