version: '3.7'

networks:
    discovery-network:

services:
  discovery-service:
    image: asia.gcr.io/${DEPLOYMENT_ENV}-contentually/discovery-service:0.0.1
    container_name: discovery-service
    restart: always
    networks:
      - discovery-network
    ports:
      - "8761:8761"
    environment:
      - DEPLOYMENT_ENV
    volumes:
      - /mnt/disks/${DEPLOYMENT_ENV}-contentually/discovery/service/log:/var/log/discovery:rw

  image-service:
    depends_on:
      - discovery-service
    networks:
      - discovery-network

  avatar-service:
    depends_on:
      - discovery-service
    networks:
      - discovery-network

  category-service:
    depends_on:
      - discovery-service
    networks:
      - discovery-network

  content-service:
    depends_on:
      - discovery-service
    networks:
      - discovery-network

  graphql-service:
    depends_on:
      - discovery-service
    networks:
      - discovery-network
