spring:
  application.name: avatar-service
  data:
    mongodb:
      host: avatar-db
      port: 27017
      authentication-database: admin
      database: avatar
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  jmx.enabled: false
server:
  port: 8083
logging:
  file:
    path: /var/log/avatar
    max-history: 14
  level:
    root: ERROR
    org.springframework.web: INFO
    com.paoperez.avatarservice: TRACE
---
spring:
  profiles: dev
eureka:
  client:
    enabled: false
---
spring:
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}
---
spring:
  profiles: prod
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}