spring:
  application.name: avatar-service
  data:
    mongodb:
      host: avatar-db
      port: 27017
      authentication-database: admin
      database: contentually
      username: ${MONGO_USERNAME:dummy_username}
      password: ${MONGO_PASSWORD:dummy_password}
  jmx.enabled: false
server:
  port: 8083
logging:
  file:
    path: /var/log/avatar
    max-history: 14
  level:
    root: ERROR
    org.springframework.web: INFO
    com.paoperez.avatarservice: TRACE
---
spring:
  profiles: development
eureka:
  client:
    enabled: false
---
spring:
  profiles: testing
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}
---
spring:
  profiles: production
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}