version: '3.7'

volumes:
  service-log:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /mnt/disks/${DEPLOYMENT_ENV}-contentually/logs/spring

services:
  discovery-service:
    image: discovery-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - DEPLOYMENT_ENV
    volumes:
      - type: volume
        source: service-log
        target: /var/log/spring
