spring:
  application.name: discovery-service
  jmx.enabled: false
server:
  port: 8761
logging:
  file:
    path: /var/log/discovery
    max-history: 14
  level:
    root: ERROR
    org.springframework.web: INFO
    com.paoperez.discoveryservice: TRACE
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false