spring:
  application.name: discovery-service
  jmx.enabled: false
server:
  port: 8761
logging:
  file:
    name: /var/log/spring/discovery.log
    max-history: 14
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false