spring:
  application.name: category-service
  data:
    mongodb:
      # uri: ${MONGO_URL:mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@category-db/category?authSource=admin}
      # uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@category-db/category?authSource=admin
      host: category-db
      port: 27017
      authentication-database: admin
      database: category
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  jmx.enabled: false
server:
  port: 8084
# logging:
#   file:
#     path: /var/log/category
#     name: spring.log
#     max-history: 14
#   level:
#     root: WARN
#     com.paoperez.categoryservice: TRACE