spring:
  application.name: category-service
  data:
    mongodb:
      host: category-db
      port: 27017
      authentication-database: admin
      database: category
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  jmx.enabled: false
server:
  port: 8084
logging:
  file:
    path: /var/log/category
    max-history: 14
  level:
    root: ERROR
    org.springframework.web: INFO
    com.paoperez.categoryservice: TRACE
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}