spring:
  application.name: category-service
  cloud:
    kubernetes:
      secrets:
        name: db-secret
        enabled: true
        enableApi: true
  data:
    mongodb:
      # uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb/categoryService
      # uri: ${MONGO_URL:mongodb://appuser:supersecret@localhost:27017/categoryService}
      # uri: ${MONGO_URL:mongodb://localhost:27017/categoryService}
      host: mongodb
      port: 27017
      database: categoryService
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  jmx.enabled: false
server:
    port: 8084