spring:
  application.name: category-service
  data:
    mongodb:
      host: category-db
      port: 27017
      authentication-database: admin
      database: contentually
      username: ${MONGO_USERNAME:dummy_username}
      password: ${MONGO_PASSWORD:dummy_password}
  jmx.enabled: false
server:
  port: 8084
logging:
  file:
    path: /var/log/category
    max-history: 14
  level:
    root: ERROR
    org.springframework.web: INFO
    com.paoperez.categoryservice: TRACE
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}
---
spring:
  profiles: local
eureka:
  client:
    enabled: false