spring:
  application.name: graphql-service
  jmx.enabled: false
server:
  port: 8080
logging:
  file:
    path: /var/log/graphql
    max-history: 14
  level:
    root: ERROR
    org.springframework.web: INFO
    com.paoperez.graphqlservice: TRACE
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10
      failureRateThreshold: 60
      registerHealthIndicator: true
  instances:
    categoryService:
      baseConfig: default
    contentService:
      baseConfig: default
    imageService:
      baseConfig: default
    avatarService:
      baseConfig: default
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}
web:
  client:
    address: http://localhost:5000
---
spring:
  profiles: local
eureka:
  client:
    enabled: false