spring:
  application.name: graphql-service
  jmx.enabled: false
server:
  port: 8080
logging:
  file:
    path: /var/log/graphql
    max-history: 14
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}
web:
  client:
    address: http://localhost:5000
---
spring:
  profiles: local
eureka:
  client:
    enabled: false