spring:
    application.name: graphql-service
server:
    port: 8090

resilience4j.circuitbreaker:
    configs:
        default:
            slidingWindowType: COUNT_BASED
            slidingWindowSize: 100
            permittedNumberOfCallsInHalfOpenState: 10
            waitDurationInOpenState: 10
            failureRateThreshold: 60
            registerHealthIndicator: true
    instances:
        categoryService:
            baseConfig: default
        contentService:
            baseConfig: default
        imageService:
            baseConfig: default
        avatarService:
            baseConfig: default
