spring:
  application.name: graphql-service
  jmx.enabled: false
server:
  port: 8080
logging:
  file:
    path: /var/log/graphql
    max-history: 14
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}
api:
  content:
    url: http://content-service/contents
  category:
    url: http://category-service/categories
  avatar:
    url: http://avatar-service/avatars
  image:
    url: http://image-service/images
---
spring:
  profiles: local
client:
  web:
    address: http://localhost:5000
