spring:
  application.name: image-service
  data:
    mongodb:
      host: image-db
      port: 27017
      authentication-database: admin
      database: image
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  jmx.enabled: false
server:
  port: 8082
logging:
  file:
    path: /var/log/image
    max-history: 14
  level:
    root: ERROR
    org.springframework.web: INFO
    com.paoperez.imageservice: TRACE
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}