spring:
  application.name: image-service
  data:
    mongodb:
      host: image-db
      port: 27017
      authentication-database: admin
      database: contentually
      username: ${MONGO_USERNAME:dummy_username}
      password: ${MONGO_PASSWORD:dummy_password}
  jmx.enabled: false
server:
  port: 8082
logging:
  file:
    path: /var/log/image
    max-history: 14
  level:
    root: ERROR
    org.springframework.web: INFO
    com.paoperez.imageservice: TRACE
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}
---
spring:
  profiles: local
eureka:
  client:
    enabled: false