spring:
  application.name: image-service
  data:
    mongodb:
      host: image-db
      port: 27017
      authentication-database: admin
      database: contentually
      username: ${MONGO_USERNAME:dummy_username}
      password: ${MONGO_PASSWORD:dummy_password}
  jmx.enabled: false
  main.banner-mode: off
server:
  port: 8082
logging:
  file:
    name: /var/log/spring/image.log
    max-history: 14
  level:
    '[org.springframework]': ERROR
    '[com.paoperez.imageservice]': INFO
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}
---
spring:
  profiles: standalone
eureka:
  client:
    enabled: false
logging:
  level:
    '[org.springframework]': DEBUG
    '[com.paoperez.imageservice]': TRACE