spring:
  application.name: image-service
  data:
    mongodb:
      # uri: ${MONGO_URL:mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@image-db/image?authSource=admin}
      # uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@image-db/image?authSource=admin
      host: image-db
      port: 27017
      authentication-database: admin
      database: image
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  jmx.enabled: false
server:
  port: 8082
# logging:
#   file:
#     path: /var/log/image
#     name: spring.log
#     max-history: 14
#   level:
#     root: WARN
#     com.paoperez.imageservice: TRACE
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}