version: '3.7'

networks:
  avatar-network:

volumes:
  data:
  dblog:
  servicelog:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /mnt/disks/logs

services:
  avatar-db:
    image: avatar-db:0.0.1
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: avatar-db
    networks:
      - avatar-network
    environment:
      - DEPLOYMENT_ENV
    volumes:
      - type: volume
        source: data
        target: /data/db
      - type: volume
        source: dblog
        target: /var/log/mongodb
      - type: bind
        source: /mnt/disks/secrets
        target: /mnt/disks/secrets
        read_only: true
  avatar-service:
    image: avatar-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: avatar-service
    depends_on:
      - avatar-db
    networks:
      - avatar-network
    ports:
      - "8083:8083"
    environment:
      - DEPLOYMENT_ENV
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV}
    volumes:
      - type: volume
        source: servicelog
        target: /var/log/spring
      - type: bind
        source: /mnt/disks/secrets
        target: /mnt/disks/secrets
        read_only: true
