version: '3.7'

networks:
  avatar-network:

services:
  avatar-db:
    image: avatar-db:0.0.1
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: avatar-db
    networks:
      - avatar-network
    volumes:
      - /mnt/disks/${DEPLOYMENT_ENV}-contentually/avatar/db/data:/data/db:rw
      - /mnt/disks/${DEPLOYMENT_ENV}-contentually/avatar/db/log:/var/log/mongodb:rw
    env_file:
      - .env
  avatar-service:
    image: avatar-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avatar-service
    depends_on:
      - avatar-db
    networks:
      - avatar-network
    ports:
      - "8083:8083"
    volumes:
      - /mnt/disks/${DEPLOYMENT_ENV}-contentually/avatar/service/log:/var/log/avatar:rw
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV}