spring:
  application.name: content-service
  data:
    mongodb:
      host: content-db
      port: 27017
      authentication-database: admin
      database: content
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  jmx.enabled: false
server:
  port: 8081
logging:
  file:
    path: /var/log/content
    max-history: 14
  level:
    root: ERROR
    org.springframework.web: INFO
    com.paoperez.contentservice: TRACE
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}