spring:
  application.name: content-service
  data:
    mongodb:
      host: content-db
      port: 27017
      authentication-database: admin
      database: contentually
      username: ${MONGO_USERNAME:dummy_username}
      password: ${MONGO_PASSWORD:dummy_password}
  jmx.enabled: false
server:
  port: 8081
logging:
  file:
    path: /var/log/content
    max-history: 14
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}
---
spring:
  profiles: standalone
eureka:
  client:
    enabled: false