apiVersion: v1
kind: Service
metadata:
  name: category-service
  labels:
    app: category-service 
spec:
  selector:
    app: category-service
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-service
  labels:
    app: category-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-service
  template:
    metadata:
      labels:
        app: category-service
    spec:
      containers:
      - name: category-service
        image: category-service:0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8084
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        # - name: MONGO_URL
        # value: mongodb://mongodb:27017/category
        # value: mongodb://appuser:supersecret@localhost:27017/categoryService