version: '3.7'

networks:
  category-network:

services:
  category-db:
    image: category-db:0.0.1
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: category-db
    volumes:
      - /mnt/disks/sdb_mnt/dev-contentually/category:/data/db:rw
      - /var/log/mongodb:/var/log/mongodb:rw
    networks:
      - category-network
    env_file:
      - dev.env
  category-service:
    image: category-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: category-service
    depends_on:
      - category-db
    # volumes:
    #   - /var/log/category:/var/log/category:rw
    networks:
      - category-network
    ports:
      - "8084:8084"
    env_file:
      - dev.env