version: '3.7'

networks:
  category-network:

volumes:
  data:
  dblog:
  servicelog:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /mnt/disks/$DEPLOYMENT_ENV-contentually/category/logs

services:
  category-db:
    image: category-db:0.0.1
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: category-db
    networks:
      - category-network
    environment:
      - DEPLOYMENT_ENV
    volumes:
      - type: volume
        source: data
        target: /data/db
      - type: volume
        source: dblog
        target: /var/log/mongodb
      - type: bind
        source: /mnt/disks/secrets
        target: /mnt/disks/secrets
        read_only: true
  category-service:
    image: category-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: category-service
    depends_on:
      - category-db
    networks:
      - category-network
    ports:
      - "8084:8084"
    environment:
      - DEPLOYMENT_ENV
      - SPRING_PROFILES_ACTIVE=${DEPLOYMENT_ENV}
    volumes:
      - type: volume
        source: servicelog
        target: /var/log/spring
      - type: bind
        source: /mnt/disks/secrets
        target: /mnt/disks/secrets
        read_only: true
